name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure ACR
        uses: azure/acr-login@v1
        with:
          name: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build web app image
        run: docker build -t ${{ secrets.ACR_NAME }}/web-app:latest . 
      - name: Push web app image to ACR
        run: docker push ${{ secrets.ACR_NAME }}/web-app:latest

      - name: Build API image
        run: docker build -t ${{ secrets.ACR_NAME }}/api-service:latest api  
      - name: Push API image to ACR
        run: docker push ${{ secrets.ACR_NAME }}/api-service:latest 

  deploy-to-app-service:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          cli_version: '2.39.0'  
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app to Azure App Service
        run: |
          az appservice webapp deploy --resource-group ${{ secrets.RESOURCE_GROUP }} \
                                       --name web-app \
                                       --plan ${{ secrets.APP_SERVICE_PLAN }} \
                                       --image ${{ secrets.ACR_NAME }}/web-app:latest

      - name: Deploy API to Azure App Service (optional)
        run: |
          az appservice webapp deploy --resource-group ${{ secrets.RESOURCE_GROUP }} \
                                       --name api-app \
                                       --plan ${{ secrets.APP_SERVICE_PLAN }} \
                                       --image ${{ secrets.ACR_NAME }}/api-service:latest 